### ISSUE TITLE
component_appid 获取错误，应该为 component 的 appId

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/wechat#149]
https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/OpenPlatform/Authorizer/OfficialAccount/OpenOAuth/Client.php#L105

应该为

`"component_appid" => $this->component[ServiceProviders::Config]->get('appId')`

或者

`"component_appid" => $this->app[ServiceProviders::Config]->get('componentAppId')`

相应的，改类 87 行也有同样错误，其他文件暂未检查。

https://github.com/easy-swoole/wechat/blob/cee56dd04f66109171ebf3009ccb52d5c177313d/src/OpenPlatform/Authorizer/OfficialAccount/OpenOAuth/Client.php#L87

**Comment by Player626** [comment]
@XueSiLf 看下

**Comment by XueSiLf** [comment]
OK



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月3日(周五) 中午11:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [easy-swoole/wechat] component_appid 获取错误，应该为 component 的 appId (#149)




 
@XueSiLf 看下
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XueSiLf** [comment]
感谢反馈，的确有问题，这边稍后修复。

**Comment by XueSiLf** [comment]
此问题已修复，详细请看 #157
